### ISSUE TITLE
Resultado Prueba 1

### ISSUE THREAD

**Issue by nbxandresvejar** [GrijalvaMarco/neubox-challenges#1]
Marco, te comparto los resultados encontrados en la primera revisión del challenge, por favor revisar cada una de ellas para poder continuar con las revisiones siguientes:
Saludos

Resultados: Marco Grijalva
Ciclo: 1

Problema 1: js
- Los nombres de archivos de entrada y salida se encuentran fijos en el código, cuando se espera robustez, es importante considerar el usar argumentos o perametros de entrada al programa.
- Hacer uso de variables claras, aún cuando de esta forma están definidas en el problema, no es claro al leerlo. Ej. m1

Problema 2: js
- Los nombres de archivos de entrada y salida se encuentran fijos en el código, cuando se espera robustez, es importante considerar el usar argumentos o perametros de entrada al programa.
- Favor de revisar las condiciones de entrada del problema y determinar cuales otros posibles errores pueden ocurrir.
- Favor de revisar la forma en como se determina el ganador.

Problema 2: python
- Los nombres de archivos de entrada y salida se encuentran fijos en el código, cuando se espera robustez, es importante considerar el usar argumentos o perametros de entrada al programa.
- Se recomienda usar programación orientada a objetos para dar solución al problema y hacer uso de prubas unitarias
- Se recomienda hacer uso del tratamiento de las excepciones dado que existe un RaiseException que no es tratada.
- Favor de revisar las condiciones de entrada del problema y determinar cuales otros posibles errores pueden ocurrir.
- Favor de revisar la forma en como se determina el ganador.

**Comment by GrijalvaMarco** [comment]
@nbxandresvejar Buenas tardes Andrés, apenas me percaté hoy de la retro, una disculpa me informó Itzel por medio de whats. Ya le di una checada más a esos comentarios, les dejo mi pr.
Sigo pendiente! Gracias y saludos!
