### ISSUE TITLE
Prueba 2

### ISSUE THREAD

**Issue by nbxandresvejar** [GrijalvaMarco/neubox-challenges#3]
Resultados: Marco Grijalva
Ciclo: 2

Problema 1: Js
- Por favor, tratar las cadenas de entrada: FILE ERROR [Error: ENOENT: no such file or directory, open '../casos/P1-CP2-LongitudLinea1Invalida.txt  '] {
    - Se recomienda usar argumentos en lugar de leer la entrada desde la consola, imagina que está automatizado, esto no lo permitiría.
P1-CP1-EntradaEjemplo: Pass, ver salida, dado que throw new Error termina de forma anormal el programa
P1-CP1-EntradaCorrecta: Pass
P1-CP2-LongitudLinea1Invalida: Pass
P1-CP3-LongitudLinea2Invalida: Pass
P1-CP4-LongitudMensajeInvalido: Pass
P1-CP5-LongitudMensajeMenor3: Pass
P1-CP6-LongitudMensajeMayor5000: Pass
P1-CP7-LongitudInstruccion1Menor2: Pass
P1-CP8-LongitudInstruccion2Menor2: Pass
P1-CP9-CaracteresInvalidosMensaje: Pass
P1-CP10-LongitudInstruccion1Mayor50: Pass
P1-CP11-LongitudInstruccion2Mayor50: Pass
P1-CP12-DosInstruccionesEnMensaje: Fail
P1-CP13-InstruccionCaracterRepetido: Pass

Problema 2: Js
- Se recomienda usar argumentos en lugar de leer la entrada desde la consola, imagina que está automatizado, esto no lo permitiría.
P2-CP01-Ejemplo: Pass
P2-CP02-GanadorP2_R7_282: Pass
P2-CP03_GanadorP1_R6_102: Pass
P2-CP04-RondasMayoresAEntrada: Fail, aún cuando no se encuentra especificada es importante identificar que otros casos de fallo pueden ocurrir.
P2-CP05-RondasMenoresAEntrada: Fail
P2-CP06-CaracteresEnNumeroRondas: Pass, cuidar salida del error
P2-CP07-CaracteresEnValorRonda: Pass, cuidar salida del error
P2-CP08-OK-Limite-10000: Fail, es necesario revisar la condición del número de rondas
P2-CP09-DesbordeDeValoresRonda: Pass

Problema 2: python 
- Se recomienda agregar archivo de requerimientos de instalación para las librerias usadas
- Se recomienda usar argumentos en lugar de leer la entrada desde la consola, imagina que está automatizado, esto no lo permitiría.
- No existe el import de la libreria requerida:
    filePath = raw_input("Please enter full path of the file: ")
    NameError: name 'raw_input' is not defined
- Existe el lanzamiento de excepciones, sin embargo no se encuentra el handler para tratarlas

**Comment by nbxandresvejar** [comment]
@GrijalvaMarco me confirmas por favor cuando estén listas las observaciones, y también en que rama. Saludos

**Comment by GrijalvaMarco** [comment]
Ya abrí un nuevo pull request Andrés.  @nbxandresvejar  Espero tus comentarios!
Gracias y saludos
https://github.com/GrijalvaMarco/neubox-challenges/pull/4
